### ISSUE TITLE
compiler versions 0.8.20 and 0.8.21 not supported getting RPC provider  error

### ISSUE THREAD

**Issue by 0xefrain** [SigmaGmbH/swisstronik-tutorials#1]
When run  ```npx hardhat run scripts/deploy.js --network swisstronik```

```ProviderError: rpc error: code = Unknown desc = evm error: InvalidCode(Opcode(95))
    at HttpProvider.request (/Users/efrain/Documents/swisstronik/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HardhatEthersProvider.estimateGas (/Users/efrain/Documents/swisstronik/node_modules/@nomicfoundation/hardhat-ethers/src/internal/hardhat-ethers-provider.ts:237:27)
    at /Users/efrain/Documents/swisstronik/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:235:35
    at async Promise.all (index 0)
    at HardhatEthersSigner._sendUncheckedTransaction (/Users/efrain/Documents/swisstronik/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:256:7)
    at HardhatEthersSigner.sendTransaction (/Users/efrain/Documents/swisstronik/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at ContractFactory.deploy (/Users/efrain/Documents/swisstronik/node_modules/ethers/src.ts/contract/factory.ts:111:24)
    at main (/Users/efrain/Documents/swisstronik/scripts/deploy.js:8:20)```

Will be good  to add these aditional  info on Contract deployment - Hardha and dev docs

![Screenshot 2023-08-12 at 1 13 03 PM](https://github.com/SigmaGmbH/swisstronik-tutorials/assets/25471030/57ac7426-d846-4a98-a151-d5ea5b7fe325)

**Comment by delneg** [comment]
Hi, looks like your screenshot failed to upload 

I'll try copypasting the link here:
![Screenshot 2023-08-12 at 1 13 03 PM](https://github.com/SigmaGmbH/swisstronik-tutorials/assets/25471030/57ac7426-d846-4a98-a151-d5ea5b7fe325)

**Comment by SantiagoDevRel** [comment]
Approved as an informational bug, thank you @0xefrain!
Please check the [Bug-Bounty-1.0 repo](https://github.com/SigmaGmbH/Bug-Bounty-1.0/tree/main/Hall%20Of%20Fame) and you will find yourself in the 'Hall of Fame' and the rewards.
