### ISSUE TITLE
eth_getStorageAt was disabled??

### ISSUE THREAD

**Issue by dieutx** [SigmaGmbH/swisstronik-tutorials#23]
Please enable the eth_getStorageAt() RPC method

[https://github.com/SigmaGmbH/swisstronik-tutorials/blob/main/Contract_verification_hardhat/scripts/deploy_verify.js](url)

error when trying to verify smart contract

`Pause finished. Verifying Contract...
Error veryfing Contract. Reason: ProviderError: eth_getStorageAt was disabled, since storage is encrypted. Check docs at https://swisstronik.gitbook.io/swisstronik-docs/ for more information
    at HttpProvider.request (/root/proxy/swisstronik-tech03-ERC721/node_modules/hardhat/src/internal/core/providers/http.ts:96:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at getStorageAt (/root/proxy/swisstronik-tech03-ERC721/node_modules/@openzeppelin/upgrades-core/src/provider.ts:75:19)
    at getStorageFallback (/root/proxy/swisstronik-tech03-ERC721/node_modules/@openzeppelin/upgrades-core/src/eip-1967.ts:51:15)
    at getImplementationAddress (/root/proxy/swisstronik-`

**Comment by Mnuralim** [comment]
Yeah, i have same issue

**Comment by dieutx** [comment]
![Untitled](https://github.com/user-attachments/assets/04754b52-c018-4399-8bc4-ba075ac18933)
yes, i think we need to vote to enable it

**Comment by delneg** [comment]
Hello,
`eth_getStorageAt` is disabled by design to prevent confusion with encrypted data

To learn more, please check out the docs:
https://swisstronik.gitbook.io/swisstronik-docs/about-swisstronik/swisstronik-vs-ethereum
