### ISSUE TITLE
Verify contract deploy

### ISSUE THREAD

**Issue by linndend** [SigmaGmbH/swisstronik-tutorials#24]
how long does it take to verify contract deployment?

output :
Successfully submitted source code for contract
contracts/Lock.sol:Lindend at 0x
for verification on the block explorer. Waiting for verification result...

already 2 hours cant execute verif

**Comment by linndend** [comment]
RPC always error sir

ProviderError: rpc error: code = Unknown desc = execution reverted
    at HttpProvider.request (/home/viinnsmoker/swisstronik_PERC-20/node_modules/hardhat/src/internal/core/providers/http.ts:96:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HardhatEthersProvider.estimateGas (/home/viinnsmoker/swisstronik_PERC-20/node_modules/@nomicfoundation/hardhat-ethers/src/internal/hardhat-ethers-provider.ts:246:27)
    at /home/viinnsmoker/swisstronik_PERC-20/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:235:35
    at async Promise.all (index 1)
    at HardhatEthersSigner._sendUncheckedTransaction (/home/viinnsmoker/swisstronik_PERC-20/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:256:7)
    at HardhatEthersSigner.sendTransaction (/home/viinnsmoker/swisstronik_PERC-20/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at sendShieldedTransaction (/home/viinnsmoker/swisstronik_PERC-20/scripts/mint.js:7:10)
    at main (/home/viinnsmoker/swisstronik_PERC-20/scripts/mint.js:21:24)
